apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: argocd-gateway
  namespace: argocd-manager
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 8080
      name: http
      protocol: HTTP
    hosts:
    - "m-argocd.bravo.com.vn"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
  namespace: argocd-manager
spec:
  hosts:
  - "m-argocd.bravo.com.vn"
  gateways:
  - argocd-gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: argocd-server
        port:
          number: 9080
